# Generated by Django 5.2.5 on 2025-12-27 01:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolatilityPipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run_label', models.CharField(default='daily_close', max_length=32)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('partial', 'partial'), ('error', 'error')], default='ok', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='VolatilityTrackedSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset_class', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolatilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rv_reference', models.CharField(choices=[('primary20', 'primary20'), ('yz20', 'yz20')], default='primary20', max_length=16)),
                ('target_dte_days', models.FloatField(default=30.0)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('error', 'error')], default='ok', max_length=16)),
                ('aha_metrics', models.JSONField(blank=True, default=dict)),
                ('iv_result', models.JSONField(blank=True, default=dict)),
                ('rv_latest', models.JSONField(blank=True, default=dict)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('raw_paths', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='main.volatilitypipelinerun')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='main.volatilitytrackedsymbol')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'symbol', 'target_dte_days', 'rv_reference'), name='uniq_vol_snapshot_per_run_symbol_dte_rvref')],
            },
        ),
        migrations.CreateModel(
            name='VolatilitySessionBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_ts', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_bars', to='main.volatilitytrackedsymbol')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'session_ts'], name='main_volati_symbol__005bf8_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'session_ts'), name='uniq_vol_session_bar_symbol_ts')],
            },
        ),
        migrations.CreateModel(
            name='ImpliedVolSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_dte_days', models.FloatField(default=30.0)),
                ('ivx_calc', models.FloatField(blank=True, null=True)),
                ('ivx_vendor', models.FloatField(blank=True, null=True)),
                ('ivx_diff', models.FloatField(blank=True, null=True)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iv_snaps', to='main.volatilitypipelinerun')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iv_snaps', to='main.volatilitytrackedsymbol')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'created_at'], name='main_implie_symbol__a9243d_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'symbol', 'target_dte_days'), name='uniq_iv_snapshot_per_run_symbol_dte')],
            },
        ),
    ]
