"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import environ

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

CACHE_DIR = BASE_DIR / 'tmp' / 'django_cache'
if not CACHE_DIR.exists():
    CACHE_DIR.mkdir(parents=True, exist_ok=True)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': str(CACHE_DIR),
        'TIMEOUT': 3600,  # in seconds, so 1 hour
        'OPTIONS': {
            'MAX_ENTRIES': 100,
        },
    }
}

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

SQLITE_PATH = env('SQLITE_PATH')
if not SQLITE_PATH:
    raise ValueError("SQLITE_PATH is not set")
if not os.path.exists(SQLITE_PATH):
    raise FileNotFoundError(f"SQLite database file not found at {SQLITE_PATH}")

TODOIST_TOKEN = env('TODOIST_TOKEN')

OWM_API_KEY = env('OWM_API_KEY')
WEATHER_CACHE_KEY = env('WEATHER_CACHE_KEY')
WEATHER_CACHE_TTL = env('WEATHER_CACHE_TTL')

LLM_API_URL = env('LLM_API_URL')
LLM_MODEL = env('LLM_MODEL')
MOTIVATION_CACHE_KEY = env('MOTIVATION_CACHE_KEY')
MOTIVATION_CACHE_TTL = env('MOTIVATION_CACHE_TTL')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY is not set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    "https://app.antibesln.com",
    # add any other origin(s) that host your front-end
]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': SQLITE_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
 
TIME_ZONE = 'America/Chicago'   # was 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Google Sheets service-account config (no env vars)
TRADING_LOG_SPREADSHEET_ID = env('TRADING_LOG_SPREADSHEET_ID')
TRADING_LOG_SA_KEY_PATH = os.path.join(BASE_DIR, "secret_store", "gcp-service-account.json")
TRADING_LOG_WORKSHEET_GID = env('TRADING_LOG_WORKSHEET_GID')
TRADING_LOG_CACHE_KEY = env('TRADING_LOG_CACHE_KEY')
TRADING_LOG_CACHE_TTL = env('TRADING_LOG_CACHE_TTL')


# Schwab API config
SCHWAB_API_KEY = env('SCHWAB_API_KEY')
SCHWAB_APP_SECRET = env('SCHWAB_APP_SECRET')
SCHWAB_CALLBACK_URL = env('SCHWAB_CALLBACK_URL')
SCHWAB_TOKEN_PATH = BASE_DIR / 'secret_store' / 'schwab_token.json'

